volumes:
  db_data:
    driver: local

networks:
  g-bank:
    name: g-bank
    driver: bridge
    external: true

services:
  postgres:
    container_name: microservices_db_java
    image: postgres:16.3
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    volumes:
      - 'db_data:/var/lib/postgresql/data'
    networks:
      - g-bank
