spring:
  application:
    name: g-bank
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5437/g-bank}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
security:
  jwt:
    secret: ${JWT_SECRET}
    access: ${JWT_ACCESS_DURATION}
    refresh: ${JWT_REFRESH_DURATION}
